---

- name: ensure configuration directories exist
  file:
    path: "{{ item }}"
    state: directory
    mode: 0750
    follow: true
  with_flattened:
    - "{{ php_conf_paths }}"
    - "{{ php_extension_conf_paths }}"

- name: ensure log directory exist
  file:
    path: "{{ php_fpm_log_directory }}"
    state: directory
    mode: 0750

- name: ensure temp directory for upload exist
  file:
    path: "{{ php_fpm_tmp_upload_diectory }}"
    state: directory
    owner: "{{ php_fpm_pool_user }}"
    group: "{{ php_fpm_pool_group }}"
    mode: 0750

- name: ensure socket directory exist
  file:
    path: "{{ php_fpm_socket_directory }}"
    state: directory
    owner: "{{ php_fpm_pool_user }}"
    group: "{{ php_fpm_pool_group }}"
    mode: 0775

- name: create php.ini configuration file
  template:
    src: php.ini.j2
    dest: "{{ item }}/php.ini"
    owner: root
    group: root
    mode: 0644
    backup: true
  loop:
    "{{ php_conf_paths }}"
  when:
    - php_use_managed_ini | bool

- name: stat php_fpm_pool_conf_path
  stat:
    path: "{{ php_fpm_pool_conf_path | dirname }}"
  register: php_fpm_pool_conf_path_dir_stat

- name: ensure the default pool directory exists
  file:
    path: "{{ php_fpm_pool_conf_path | dirname }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  when:
    - php_fpm_pool_conf_path_dir_stat.stat.islnk is not defined

- name: create php-fpm.conf
  template:
    src: php-fpm.conf.j2
    dest: "{{ php_fpm_conf_path }}/php-fpm.conf"
    owner: root
    group: root
    force: true
    mode: 0644
  notify:
    - restart php-fpm

- block:
    - name: ensure the modules directory {{ php_modules_conf_paths }} exists
      file:
        path: "{{ php_modules_conf_paths }}"
        state: directory
        owner: root
        group: root
        mode: 0750
      when:
        - php_modules_conf_paths is defined

    - name: configure modules
      template:
        src: php_module.ini.j2
        dest: "{{ php_modules_conf_paths }}/{{ item.name }}.ini"
        mode: 0644
      when: item.enabled | bool | default(false)
      with_items:
        '{{ php_modules }}'

    - name: enable modules
      file:
        src: "{{ php_modules_conf_paths }}/{{ item.0.name }}.ini"
        dest: "{{ item.1 }}{{ '/conf.d/' if ansible_os_family | lower != 'redhat' else '/' }}{{ item.0.priority | default(20) }}-{{ item.0.name }}.ini"
        state: link
        force: true
      when:
        - item.0.enabled | bool | default(false)
      with_nested:
        - '{{ php_modules }}'
        - "{{ php_conf_paths }}"
      notify:
        - restart php-fpm

    - name: disable modules
      file:
        path: "{{ item.1 }}{{ '/conf.d/' if ansible_os_family | lower != 'redhat' else '/' }}{{ item.0.priority | default(20) }}-{{ item.0.name }}.ini"
        state: absent
      when:
        - not item.0.enabled | bool | default(false)
      with_nested:
        - '{{ php_modules }}'
        - "{{ php_conf_paths }}"
      notify:
        - restart php-fpm

  when:
    - php_modules_conf_paths is defined

...
