---

- name: include OS specific configuration
  include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      paths:
        - "vars"
      files:
        # eg. debian-10 / ubuntu-20.04 / centos-8 / oraclelinux-8
        - "{{ ansible_distribution | lower }}-{{ ansible_distribution_major_version }}.yaml"
        # eg. archlinux-systemd / archlinux-openrc
        - "{{ ansible_distribution | lower }}-{{ ansible_service_mgr | lower }}.yaml"
        # eg. debian / ubuntu / centos / oraclelinux
        - "{{ ansible_distribution | lower }}.yaml"
        # eg. redhat / debian / archlinux
        - "{{ ansible_os_family | lower }}.yaml"
        - default.yaml
      skip: true

- block:
    # RPM-GPG-KEY-remi2018: the GnuPG public key of the key pair used to sign my packages (Fedora 28-29 and EL-8)
    # RPM-GPG-KEY-remi2017: the GnuPG public key of the key pair used to sign my packages (Fedora 26-27)
    # RPM-GPG-KEY-remi    : the GnuPG public key of the key pair used to sign my packages (Fedora <= 25 and EL <= 7)
    - name: import remi2018 GPG key.
      rpm_key:
        key: https://rpms.remirepo.net/RPM-GPG-KEY-remi2018
        state: present
      when:
        - ansible_distribution_major_version | int >= 8

    - name: import remi GPG key.
      rpm_key:
        key: http://rpms.remirepo.net/RPM-GPG-KEY-remi
        state: present
      when:
        - ansible_distribution_major_version | int <= 7

    - name: import EPEL GPG key.
      rpm_key:
        key: https://archive.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-{{ ansible_distribution_major_version }}
        state: present

    - name: install EPEL repository
      yum_repository:
        name: epel
        state: present
        description: Extra Packages for Enterprise Linux {{ ansible_distribution_major_version }} - $basearch
        baseurl: http://download.fedoraproject.org/pub/epel/{{ ansible_distribution_major_version }}/$basearch
        gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-{{ ansible_distribution_major_version }}
        metalink: https://mirrors.fedoraproject.org/metalink?repo=epel-{{ ansible_distribution_major_version }}&arch=$basearch&infra=$infra&content=$contentdir
        failovermethod: priority
        gpgcheck: 1
        enabled: 1

    - name: install remi repository
      package:
        name: http://rpms.remirepo.net/enterprise/remi-release-{{ ansible_distribution_major_version }}.rpm
        state: present

    # https://bugs.centos.org/view.php?id=16604
    - name: activate PowerTools repository
      template:
        src: yum.repos.d/CentOS-Linux-PowerTools.repo.j2
        dest: /etc/yum.repos.d/CentOS-Linux-PowerTools.repo
        mode: 0644
      when:
        - ansible_os_family | lower == 'redhat'
        - not ansible_distribution | lower == "oraclelinux"
        - ansible_distribution_version | int >= 8
  when:
    - ansible_os_family | lower == 'redhat'

- name: update package cache
  package:
    update_cache: true

- name: do facts module to get latest information
  setup:
    gather_subset:
      - '!all'
      - '!any'
      - facter

- name: define pool user
  set_fact:
    php_fpm_pool_user: "{{ php_fpm_pool_user_default }}"
  when:
    - not php_fpm_pool_user is defined or php_fpm_pool_user | length == 0

- block:
    - name: "find primary group for user '{{ php_fpm_pool_user }}'"
      getent:
        database: group
        key: "{{ php_fpm_pool_user }}"
        split: ':'

    - name: "set php_fpm_pool_group '{{ getent_group | list | first }}'"
      set_fact:
        php_fpm_pool_group: "{{ getent_group | list | first }}"
      when:
        - getent_group is defined
  when:
    - not php_fpm_pool_group is defined or php_fpm_pool_group | length == 0

- name: assert pool group
  assert:
    that:
      - php_fpm_pool_group is defined or php_fpm_pool_group | length == 0
    msg: no php-fpm pool group detected
    quiet: true

- name: create ansible local facts directory
  file:
    dest: /etc/ansible/facts.d
    state: directory
    owner: root
    group: root
    mode: 0775

...
